env:
  - GHCVER=7.6.3
  - GHCVER=7.8.2
before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install darcs libgmp3-dev libgmp3c2 freeglut3 freeglut3-dev
  - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:$PATH
install:
  - cabal-1.18 install gtk2hs-buildtools
script:
  - cabal-1.18 install
notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
    skip_join: true
  email: true
